name: "Fetch GitHub Copilot Metrics"
description: "Fetches the usage metrics for GitHub Copilot"
author: "RickardHF"
branding:
  icon: "activity"
  color: "blue"

inputs:
  token:
    description: "GitHub token, should be a token from a GitHub App or a PAT"
    required: true
  org:
    description: "The organization to fetch metrics for"
    required: true
  file-name:
    description: "The name of the file to write the metrics to"
    required: true
    default: "copilot-metrics"

runs:
  using: "node20"
  main: "dist/index.js"
